repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.51.0 # Update with the desired eslint version
    hooks:
      - id: eslint
        args: [--fix]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0 # Update with the desired prettier version
    hooks:
      - id: prettier
        args: [--write, .]
